# Generated by Django 5.1.1 on 2025-02-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='investimento',
            name='categoria',
            field=models.CharField(choices=[('RF', 'Renda Fixa'), ('RV', 'Renda Variável'), ('CR', 'Criptomoeda'), ('FI', 'Fundos Imobiliários')], max_length=2),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='rentabilidade_anual',
            field=models.FloatField(help_text='Rentabilidade em percentual (ex: 5.5 para 5,5%)'),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='valor_investido',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
