# Generated by Django 5.1.6 on 2025-02-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0004_alter_investimento_usuario'),
    ]

    operations = [
    ]
